title: Rija Ansari # your name (or website title) here
logo: "/images/rijaheadshot.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Experienced chemist solving problems with data science through artificial intelligence, data visualization, machine learning and storytelling. 
  <br><br>
  <a href="https://www.linkedin.com/in/rija-ansari/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
